# Generated by Django 5.0.10 on 2024-12-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InforUser',
        ),
    ]
